pages/config/routes.rb
Refinery::Core::Engine.routes.draw do
  root to: 'pages#home', via: :get
  get '/pages/:id', to: 'pages#show', as: :page

  namespace :pages, path: '' do
    namespace :admin, path: Refinery::Core.backend_route do
      scope path: :pages do
        post 'preview', to: 'preview#show', as: :preview_pages
        patch 'preview/*path', to: 'preview#show', as: :preview_page
      end
    end
  end

  namespace :admin, path: Refinery::Core.backend_route do
    get 'pages/*path/edit', to: 'pages#edit', as: 'edit_page'
    get 'pages/*path/children', to: 'pages#children', as: 'children_pages'
    patch 'pages/*path', to: 'pages#update', as: 'update_page'
    delete 'pages/*path', to: 'pages#destroy', as: 'delete_page'

    resources :pages, except: :show do
      post :update_positions, on: :collection
    end

    resources :pages_dialogs, only: [] do
      collection do
        get :link_to
      end
    end

    resources :page_parts, only: [:new, :create, :destroy]
  end
end

pages/app/views/refinery/admin/pages/_actions.html.erb
<ul>
  <li><%= render '/refinery/admin/search', url: refinery.admin_pages_path -%></li>
  <li>
    <%= action_label :add, refinery.new_admin_page_path, t('.create_new_page') %>
  </li>
<% if @pages.many? and !searching? %>
  <li>
    <%= action_label :reorder, refinery.admin_pages_path, t('.reorder_pages'), id: 'reorder_action'%>
    <%= action_label :reorder_done, refinery.admin_pages_path, t('.reorder_pages_done'), id: 'reorder_action_done', class: 'hidden'%>
  </li>
<% end %>
</ul>

pages/app/views/refinery/admin/pages/_form.html.erb
<%= form_for [refinery, :admin, @page],
             :url => (refinery.admin_update_page_path(@page.nested_url) if @page.persisted?) do |f| %>

  <%= render '/refinery/admin/error_messages', :object => @page, :include_object_name => true %>

  <%= render '/refinery/admin/locale_picker', :current_locale => Mobility.locale %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "larger widest" %>
  </div>

  <%= render 'form_fields_after_title', :f => f %>

  <div class='field'>
    <%= render 'form_page_parts', :f => f %>
  </div>

  <%= render 'form_advanced_options', :f => f %>

  <%= render '/refinery/admin/form_actions', f: f,
             continue_editing: true,
             delete_title: t('delete', scope: 'refinery.admin.pages'),
             delete_confirmation: t('message', scope: 'refinery.admin.delete', title: @page.title),
             before_cancel_button: submit_tag(
               t('.preview'),
               id: 'preview-button',
               title: 'Preview page',
               name: nil,
               class: 'wymupdate button',
               tooltip: t('.preview_changes'),
               data: { disable_with: false }
             ),
             cancel_url: refinery.admin_pages_path %>

  <%= render 'form_new_page_parts', :f => f if Refinery::Pages.new_page_parts %>
<% end %>

<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(
        <%= Refinery::Pages.new_page_parts.to_s %>
        , "<%= refinery.new_admin_page_part_path %>"
        , "<%= refinery.admin_page_parts_path %>"
      );

      $( '#preview-button' ).on( 'click', function(e) {
        e.preventDefault();

        var $form = $(this).parents('form');
        var prev_url = $form.attr('action');
        var prev_target = $form.attr('target') || '';

        $form.attr({
          action: '<%= @page.persisted? ? refinery.pages_admin_preview_page_path(@page.nested_url) : refinery.pages_admin_preview_pages_path %>',
          target: '_blank'
        })

        $form.submit();

        setTimeout(function(){
          $form.attr({
            action: prev_url,
            target: prev_target
          });
        }, 100);
      });
    });
  </script>
<% end %>

pages/app/views/refinery/admin/pages/_form_advanced_options.html.erb
<%= render '/refinery/admin/form_advanced_options_menu', :f => f %>

<div id="more_options" style="display:none;">
  <div class="hemisquare">
    <h2><%= t('.page_options') %></h2>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :parent_id, t('.parent_page') %>
        <%= refinery_help_tag t('.parent_page_help')%>
      </span>
      <%= f.select :parent_id, parent_id_nested_set_options(@page), :include_blank => true %>
    </div>
    <% if Refinery::Pages.use_layout_templates %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :layout_template, t('.layout_template') %>
        <%= refinery_help_tag t('.layout_template_help') %>
      </span>
      <%= f.select :layout_template, valid_layout_templates,
                   template_options(:layout_template, @page) %>
    </div>
    <% end %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :view_template, t('.view_template') %>
        <%= refinery_help_tag t('.view_template_help') %>
      </span>
      <%= f.select :view_template, valid_view_templates.map { |t| [t.titleize, t] },
                   template_options(:view_template, @page) %>
    </div>

    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :menu_title, t('.menu_title') %>
        <%= refinery_help_tag t('.menu_title_help') %>
      </span>
      <%= f.text_field :menu_title, :style=> 'width:400px;' %>
    </div>
    <% if Refinery::Pages.use_custom_slugs %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :custom_slug, t('.custom_slug') %>
        <%= refinery_help_tag t('.custom_slug_help') %>
      </span>
      <%= f.text_field :custom_slug, :style=> 'width:400px;' %>
    </div>
    <% end %>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :skip_to_first_child?, t('.skip_to_first_child') %>
        <%= refinery_help_tag t('.skip_to_first_child_help') %>
      </span>
      <%= f.check_box :skip_to_first_child %>
      <%= f.label :skip_to_first_child, t('.skip_to_first_child_label'),
                  :class => "stripped" %>
    </div>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :link_url, t('.link_url') %>
        <%= refinery_help_tag t('.link_url_help') %>
      </span>
      <%= f.text_field :link_url, :style=> 'width:400px;' %>
      <% content_for :javascripts do %>
      <script>
        $(document).ready(function(){
          link_tester.validate_url_textbox("#page_link_url")
        });
      </script>
      <% end %>
    </div>
    <div class='field'>
      <span class='label_with_help'>
        <%= f.label :show_in_menu, t('.show_in_menu_title'),
                    :id => 'page_show_in_menu_heading' %>
        <%= refinery_help_tag t('.show_in_menu_help') %>
      </span>
      <%= f.check_box :show_in_menu %>
      <%= f.label :show_in_menu, t('.show_in_menu_description'),
                  :class => "stripped" %>
    </div>

    <%= render 'form_extra_fields_for_more_options', :f => f %>
  </div>

  <%= render 'form_advanced_options_seo', :f => f %>
</div>

pages/app/views/refinery/admin/pages/_form_advanced_options_seo.html.erb
<div class="hemisquare right_side">
  <%= render '/seo_meta/form', :form => f %>
</div>

pages/app/views/refinery/admin/pages/_form_extra_fields_for_more_options.html.erb
<%# Intentionally empty, useful override point to add extra fields. %>

pages/app/views/refinery/admin/pages/_form_fields_after_title.html.erb
<%# Intentionally empty, useful override point to add extra fields. %>

pages/app/views/refinery/admin/pages/_form_new_page_parts.html.erb
<div id='new_page_part_dialog' style='display: none'>
  <div class='field'>
    <label for='new_page_part_title'><%= t('.title')  %></label>
    <input id='new_page_part_title' value='' class='larger widest' />

    <label for='new_page_part_slug'><%= t('.slug')  %></label>
    <input id='new_page_part_slug' value='' class='larger widest' />

    <input id='new_page_part_index' type='hidden' value='<%= @page.parts.size %>' />
  </div>
  <%= render '/refinery/admin/form_actions', :f => f,
             :continue_editing => false,
             :submit_button_id => "new_page_part_save",
             :cancel_button_id => "new_page_part_cancel",
             :hide_delete => true %>
</div>

<% content_for :after_javascript_libraries do %>
  <%= javascript_include_tag 'speakingurl' %>
<% end %>

pages/app/views/refinery/admin/pages/_page.html.erb
<% # setup params for various action links
  add_url =   refinery.new_admin_page_path(parent_id: page.id)
  edit_url =  refinery.admin_edit_page_path(page.nested_url, switch_locale: (page.translations.first.locale unless page.translated_to_default_locale?))
  delete_url = refinery.admin_delete_page_path(page.nested_url)
  delete_options = {
     class: "cancel confirm-delete",
            data: {confirm: t('message',  scope: 'refinery.admin.delete', title: translated_field(page, :title))}
          }
 %>

  <li class='clearfix record items' id="<%= dom_id(page) -%>">
  <div class='clearfix'>
    <% if page.children.present? %>
      <span class="item icon toggle <%= 'expanded' if Refinery::Pages.auto_expand_admin_tree %>"
        title="<%= t('expand_collapse', scope: 'refinery.admin.pages')%>">
      </span>
    <% else %>
      <span class="item"></span>
    <% end %>

    <span class='title <%= 'toggle' if page.children.present? %>'>
      <%= translated_field(page, :title) %>
      <%= page_meta_information page %>
    </span>

    <% if Refinery::I18n.frontend_locales.many? %>
      <span class='locales'>
        <% page.translations.sort_by{ |t| Refinery::I18n.frontend_locales.index(t.locale)}.each do |translation| %>
          <% if translation.title.present? %>
            <%= link_to refinery.admin_edit_page_path(page.nested_url, switch_locale: translation.locale),
                        class: 'locale', title: translation.locale.upcase do %>

              <div class="<%=translation.locale %> locale_marker">
                <%= locale_text_icon(translation.locale.upcase) %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </span>
    <% end %>

    <span class='actions'>
      <%= action_icon(:preview, page.url,   t('.view_live_html')) %>
      <%= action_icon(:add,     add_url,    t('new',    scope: 'refinery.admin.pages' ) ) %>
      <%= action_icon(:edit,    edit_url ,  t('edit',   scope: 'refinery.admin.pages' ) ) %>
      <%= action_icon(:delete,  delete_url, t('delete', scope: 'refinery.admin.pages' ), delete_options ) if page.deletable? %>
    </span>
  </div>

  <%= content_tag :ul, class: 'nested', data: { 'ajax-content': refinery.admin_children_pages_path(page.nested_url) } do %>
    <%= render(partial: 'page', collection: page.children, cached: ->(child_page) { child_page.self_and_descendants }) if Refinery::Pages.auto_expand_admin_tree %>
  <% end %>
</li>

pages/app/views/refinery/admin/pages/_page_part_field.html.erb
<div class='page_part' id='<%= new_part ? "page_part_new_#{part_index}" : part.to_param %>'>
  <%= hidden_field_tag "page[parts_attributes][#{part_index}][title]", part.title if new_part %>
  <%= hidden_field_tag "page[parts_attributes][#{part_index}][slug]", part.slug if new_part %>
  <%= text_area_tag "page[parts_attributes][#{part_index}][body]", part.body, :rows => 20, :class => 'visual_editor widest' %>
  <%= hidden_field_tag "page[parts_attributes][#{part_index}][position]", part_index %>
</div>

pages/app/views/refinery/admin/pages/_save_and_continue_callback.html.erb
<%= render '/refinery/message' %>
<%= hidden_field_tag 'new_action', local_assigns[:new_refinery_page_path] %>
<%= hidden_field_tag 'new_refinery_edit_page_path', local_assigns[:new_refinery_edit_page_path] %>
<script>refinery_page_preview_url = '<%= local_assigns[:new_page_path] %>';</script>

pages/app/views/refinery/admin/pages/_sortable_list.html.erb
<%= content_tag :ul, id: 'sortable_list' do %>
  <%= render partial: 'page', collection: @pages.roots, cached: ->(child_page) { child_page.self_and_descendants } %>
<% end %>

<%= render '/refinery/admin/sortable_list', continue_reordering: !!local_assigns[:continue_reordering] %>

pages/app/views/refinery/admin/pages/children.html.erb
<%= render partial: 'page', collection: @page.children, cached: ->(child_page) { child_page.self_and_descendants } %>

pages/app/views/refinery/admin/pages/edit.html.erb
<%= render 'form' %>

pages/app/views/refinery/admin/pages/index.html.erb
<section id='records' class='tree'>
  <%= render 'records' %>
</section>
<section id='actions'>
  <%= render 'actions' %>
</section>
<%= render '/refinery/admin/make_sortable', options: {tree: true, replaceContentsAfterUpdate: true} if @pages.many? -%>